### ISSUE TITLE
Space Exploration compatibility

### ISSUE THREAD

**Issue by SIGSTACKFAULT** [mbakulin/ltn_screensaver#2]
If using Space Exploration's *Navigation Satellite Uplink* mode, the mod fails horribly and causes a crash to menu.

should at least show an error popup instead of causing a crash.

**Comment by mbakulin** [comment]
Can you please provide a save and steps to reproduce?

**Comment by SIGSTACKFAULT** [comment]
Working on it. Also, the screensaver follows trains on Nauvis regardless of what surface the player is on.

**Comment by SIGSTACKFAULT** [comment]
Oop, nope, correction, it follows trains from *all surfaces* at *all times*.

it just happens that Nauvis is the overwhelming majority of trains in my survival world, so it looks like it's only Nauvis.

**Comment by SIGSTACKFAULT** [comment]
video of me reproducing the bugs: https://youtu.be/f7EpHI8i028

savefile: [ltn-screensaver-issue-2.zip](https://github.com/mbakulin/ltn_screensaver/files/7927023/ltn-screensaver-issue-2.zip)

**Comment by mbakulin** [comment]
I've pushed an update. It's not in the factorio modbase yet, but you can download the updated source from github. Please try it. I can't easily switch surfaces myself because it conflicts with the way Space Exploration works, so I've made so that screensaver uses only trains from the surface the player is on (or is looking at if you use satellite view).

**Comment by SIGSTACKFAULT** [comment]
Seems to work!
